// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPxusUKeJUM0vAeY3GjkLWZiEDq6iAT4',
    appId: '1:265876319379:web:beb705df9854ee548f7166',
    messagingSenderId: '265876319379',
    projectId: 'gsg-chat-app',
    authDomain: 'gsg-chat-app.firebaseapp.com',
    storageBucket: 'gsg-chat-app.appspot.com',
    measurementId: 'G-MXGSLR7GGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHo7AcvfbPS2IeE16QPpnIqKkik7jXCM',
    appId: '1:265876319379:android:3cd0d5d2bf575b968f7166',
    messagingSenderId: '265876319379',
    projectId: 'gsg-chat-app',
    storageBucket: 'gsg-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_iNi1ZbYJUgmwLNHkEtM6MxLmJdho5LY',
    appId: '1:265876319379:ios:838857ded037c63f8f7166',
    messagingSenderId: '265876319379',
    projectId: 'gsg-chat-app',
    storageBucket: 'gsg-chat-app.appspot.com',
    iosClientId: '265876319379-s63nm3cscrq0n0n1nner5ma02ta4vrv8.apps.googleusercontent.com',
    iosBundleId: 'com.msa2002.chatApp',
  );
}
